name: 'stellantis_dbt'
version: '1.0.0'
config-version: 2


name: 'stellantis_dbt'
version: '1.0.0'
config-version: 2


profile: 'stellantis_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# On-run hooks (execute before/after dbt run)
on-run-start:
  - "{{ log_run_info() }}"
on-run-end:
  - "{{ log('dbt run completed successfully!', info=True) }}"

models:
  stellantis_dbt:
    # Staging layer
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging', 'source']
    
    # Intermediate layer
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ['intermediate', 'transformation']
    
    # Marts layer
    marts:
      +materialized: table
      +schema: marts
      +tags: ['marts', 'analytics']
      # Post-hook: Analyze tables after creation for query optimization
      +post-hook:
        - "ANALYZE {{ this }}"
    
    # Dimensions layer
    dimensions:
      +materialized: table
      +schema: dimensions
      +tags: ['dimensions', 'scd']
      +post-hook:
        - "ANALYZE {{ this }}"
models:
  stellantis_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
    dimensions:
      +materialized: incremental
      +schema: dimensions


profile: 'stellantis_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stellantis_dbt:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

